name: Daily NSE Prediction Pipeline

on:
  workflow_dispatch:
  schedule:
    # 11:30 UTC is 17:00 IST, Mon–Fri
    - cron: '30 11 * * 1-5'


jobs:
  build-and-evaluate:
    runs-on: windows-latest   # ← switch to Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Download trained model
        shell: bash            # use bash even on Windows
        run: |
          mkdir -p models
          curl -L -o models/XGB_backward.pkl \
             https://github.com/Amithsk/nsetradingbot/releases/download/V2.0/XGB_backward.pkl
          curl -L -o models/RF_backward.pkl \
            https://github.com/Amithsk/nsetradingbot/releases/download/V2.0/RF_backward.pkl
          curl -L -o models/LGBM_backward.pkl \
            https://github.com/Amithsk/nsetradingbot/releases/download/V2.0/LGBM_backward.pkl
          curl -L -o models/Logistic_backward.pkl \
            https://github.com/Amithsk/nsetradingbot/releases/download/V2.0/Logistic_backward.pkl

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backward script $ commit the files
        shell: bash
        run: |
          # Run python code
          python Code/nsebackwardbot.py

          # Read the folder value that the Python code wrote for the git action
          folder_date=$(cat folder_date.txt)

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Output/$folder_date/backward/nifty_LGBM_backward_$folder_date.csv
          git add Output/$folder_date/backward/nifty_Logistic_backward_$folder_date.csv
          git add Output/$folder_date/backward/nifty_RF_backward_$folder_date.csv
          git add Output/$folder_date/backward/nifty_XGB_backward_$folder_date.csv 
          git add Output/$folder_date/backward/model_metrics_$folder_date.csv       
          git commit -m "Backward  evaluation for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
      
      - name: Run forward script & commit the files
        shell: bash
        run: |

          # Run the python code
          python Code/nsepredictionbot.py
      

          # Read the tstr value that the Python code wrote for the git action
          folder_date=$(cat tstr.txt)

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Output/$folder_date/forward/nifty_LGBM_forward_$folder_date.csv
          git add Output/$folder_date/forward/nifty_Logistic_forward_$folder_date.csv
          git add Output/$folder_date/forward/nifty_RF_forward_$folder_date.csv
          git add Output/$folder_date/forward/nifty_XGB_forward_$folder_date.csv
          git add Output/$folder_date/forward/forward_summary_$folder_date.csv 
          git commit -m "Forward  evaluation for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}


      - name: Run the merged evaluation & commit the files
        shell: bash
        run: |
          python Code/nseevaluationscript.py      
         
          # Read the today_str value that the Python code wrote for the git action
          folder_date=$(cat today_str.txt)

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Output/$folder_date/evaluation/evaluation_summary_$folder_date.csv          
          git commit -m "Automated evaluation for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}

      - name: Cleanup temp files
        shell: bash
        run: |
          rm -f tstr.txt
          rm -f today_str.txt
          rm -f folder_date.txt
