name: Daily NSE Prediction Pipeline

on:
  workflow_dispatch:
  schedule:
    # 11:30 UTC is 17:00 IST, Mon–Fri
    - cron: '30 11 * * 1-5'


jobs:
  build-and-evaluate:
    runs-on: windows-latest   # ← switch to Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Download trained model
        shell: bash            # use bash even on Windows
        run: |
          mkdir -p models
          curl -L -o models/XGB_backward.pkl \
             https://github.com/Amithsk/nsetradingbot/releases/download/V2.0/XGB_backward.pkl
          curl -L -o models/RF_backward.pkl \
            https://github.com/Amithsk/nsetradingbot/releases/download/V2.0/RF_backward.pkl
          curl -L -o models/LGBM_backward.pkl \
            https://github.com/Amithsk/nsetradingbot/releases/download/V2.0/LGBM_backward.pkl
          curl -L -o models/Logistic_backward.pkl \
            https://github.com/Amithsk/nsetradingbot/releases/download/V2.0/Logistic_backward.pkl

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backward script
        shell: bash
        run: |
          python Code/nsebackwardbot.py
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Output/nifty_LGBM_*.csv
          git add Output/nifty_Logistic_*.csv
          git add Output/nifty_RF_*.csv
          git add Output/nifty_XGB_*.csv        
          git commit -m "Backward  evaluation for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
      
      - name: Run forward script
        shell: bash
        run: |

          python Code/nsepredictionbot.py
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Output/nifty_LGBM_forward_*.csv
          git add Output/nifty_Logistic_forward_*.csv
          git add Output/nifty_RF_forward_*.csv
          git add Output/nifty_XGB_forward_*.csv  
          git commit -m "Forward  evaluation for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}


      - name: Run the merged evaluation
        shell: bash
        run: python Code/nseevaluationscript.py

      - name: Commit evaluation output
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Output/evaluation_summary_*.csv          
          git commit -m "Automated evaluation for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
