name: Daily NSE Prediction Pipeline

on:
  workflow_dispatch:
  schedule:
    # 11:30 UTC is 17:00 IST, Mon–Fri
    - cron: '30 11 * * 1-5'


jobs:
  build-and-evaluate:
    runs-on: windows-latest   # ← switch to Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download trained model
        shell: bash            # use bash even on Windows
        run: |
          mkdir -p models
          curl -L -o models/dqn_nifty_final.zip \
            https://github.com/Amithsk/nsetradingbot/releases/download/V1.0/dqn_nifty_final.zip

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backward script
        shell: bash
        run: |
          python Code/nsebackwardbot.py
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Output/nifty_xgb_backward_*.csv
          git commit -m "Backward  evaluation for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
      
      - name: Run forward script
        shell: bash
        run: |

          python Code/nsepredictionbot.py
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Output/nifty_xgb_forward_*.csv
          git commit -m "Forward  evaluation for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}


      - name: Run the merged evaluation
        shell: bash
        run: python Code/nseevaluationscript.py

      - name: Commit evaluation output
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Output/predictions_comparison_*.csv Output/daily_summary_*.csv
          git commit -m "Automated evaluation for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
